Config As screen:
    OnVisible: |-
        =If( Connection.Connected,
        UpdateContext({varConfig: "Administradores"}),
        UpdateContext({varConfig: "Áreas"}))

    Image10 As image:
        Height: =1051
        Image: =backgroundSideman
        ImagePosition: =ImagePosition.Fill
        Width: =Parent.Width
        Y: =85
        ZIndex: =1

    HtmlText1_4 As htmlViewer:
        Height: =971
        HtmlText: |-
            ="<div 
            style='width: 615px; height: 925px;box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px; margin: auto; margin-top: 12px'>
            </div>"
        PaddingBottom: =0
        PaddingLeft: =0
        PaddingRight: =0
        PaddingTop: =0
        Width: =640
        Y: =85
        ZIndex: =2

    divider_menu As rectangle:
        Fill: =RGBA(153, 153, 153, 1)
        Height: =2
        Width: =620
        X: =10
        Y: =1036
        ZIndex: =3

    glrMenu As gallery.galleryHorizontal:
        Height: =111
        Items: =AdministratorMenu
        ShowScrollbar: =false
        TemplateSize: =163
        Width: =505
        X: =68
        Y: =103
        ZIndex: =7

        lbMenu As label:
            Align: =Align.Center
            Font: =Font.'Lato Light'
            FontWeight: =FontWeight.Semibold
            Height: =36
            OnSelect: =Select(Parent)
            PaddingLeft: =0
            PaddingRight: =0
            Size: =14
            Text: =ThisItem.Title
            Width: =163
            Y: =58
            ZIndex: =1

        icon As icon.Search:
            Color: =RGBA(0, 188, 255, 1)
            DisplayMode: =If( varConfig = ThisItem.Title, DisplayMode.Edit, DisplayMode.Disabled)
            Height: =60
            Icon: =ThisItem.Icon
            OnSelect: =Select(Parent)
            Width: =60
            X: =51
            Y: =4
            ZIndex: =2

        background As htmlViewer:
            Fill: =RGBA(0, 0, 0, 0)
            Height: =106
            HtmlText: |-
                ="
                <div style='margin-top:10px;margin:auto;width:157px; height:100px;box-shadow: rgba(0, 0, 0, 0.16) 0px 1px 4px;'>
                </div>
                "
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Width: =163
            ZIndex: =3

        button As button:
            BorderThickness: =0
            DisplayMode: =If( Connection.Connected, DisplayMode.Edit, DisplayMode.Disabled)
            Fill: =RGBA(0, 0, 0, 0)
            FocusedBorderThickness: =0
            Height: =100
            HoverFill: =RGBA(0, 0, 0, 0.1)
            OnSelect: |-
                =UpdateContext({varConfig: ThisItem.Title})
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            PressedFill: =RGBA(0, 0, 0, 0.4)
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Size: =24
            Text: =""
            Tooltip: =ThisItem.Title
            Width: =157
            X: =3
            ZIndex: =4

        divider As rectangle:
            DisplayMode: =DisplayMode.Disabled
            Fill: =If( varConfig = ThisItem.Title, RGBA(0, 188, 255, 1),RGBA(244, 244, 244, 1))
            Height: =2
            OnSelect: =Select(Parent)
            X: =7
            Y: =96
            ZIndex: =5

    glrItens As gallery.galleryVertical:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Height: =If( varConfig <> "Administradores", 590, 530)
        Items: |
            =
        Layout: =Layout.Vertical
        TemplateSize: =142
        Width: =607
        X: =17
        Y: =If( varConfig <> "Administradores", 422, 482)
        ZIndex: =8

    lbRegistro As label:
        Align: =Align.Center
        Font: =Font.'Lato Light'
        FontWeight: =FontWeight.Semibold
        Height: =60
        OnSelect: =
        Size: =21
        Text: ="Registro " & varConfig
        Width: =607
        X: =17
        Y: =227
        ZIndex: =9

    cbUsuario As combobox:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        ChevronBackground: =RGBA(0, 188, 255, 1)
        ChevronHoverBackground: =ColorFade(RGBA(0, 188, 255, 1), -20%)
        DisplayFields: =["Mail","DisplayName"]
        FocusedBorderThickness: =2
        Font: =Font.'Lato Light'
        FontWeight: =FontWeight.Semibold
        Height: =50
        HoverFill: =RGBA(255, 255, 255, 1)
        InputTextPlaceholder: ="Usuario"
        IsSearchable: =false
        Items: |
            =If( Connection.Connected,
            UsuáriosdoOffice365.SearchUser({searchTerm:cbUsuario.SearchText}),
            ["Sin conexión"])
        PressedFill: =RGBA(0, 188, 255, 1)
        SearchFields: =["City"]
        SearchItems: =[]
        SelectionFill: =ColorFade(RGBA(0, 188, 255, 1), -20%)
        SelectMultiple: =false
        Size: =18
        Template: =ListItemTemplate.Person
        Tooltip: ="Seleccionar usuario"
        Visible: =If(varConfig = "Administradores",true,false)
        Width: =607
        X: =17
        Y: =287
        ZIndex: =10

    dpCategoria As dropdown:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        ChevronBackground: =RGBA(0, 188, 255, 1)
        ChevronHoverBackground: =ColorFade(RGBA(0, 188, 255, 1), -20%)
        FocusedBorderThickness: =2
        Font: =Font.'Lato Light'
        FontWeight: =FontWeight.Semibold
        Height: =50
        HoverFill: =RGBA(255, 255, 255, 1)
        Items: =DropDownSample
        PressedFill: =RGBA(0, 188, 255, 1)
        SelectionFill: =ColorFade(RGBA(0, 188, 255, 1), -20%)
        Size: =18
        Tooltip: ="Seleccione el nivel de usuario"
        Visible: =If(varConfig = "Administradores",true,false)
        Width: =607
        X: =17
        Y: =352
        ZIndex: =11

    btRegistro As button:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =1
        Color: =RGBA(0, 0, 0, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        Fill: =RGBA(137, 211, 41, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        FocusedBorderThickness: =2
        Font: =Font.'Lato Light'
        Height: =50
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverFill: =ColorFade(Self.Fill, -25%) 
        OnSelect: |-
            =/*Administradores*/
            If(
                varConfig = "Administradores",
                If(
                    !IsBlank(cbUsuario.Selected) And !IsBlank(dpCategoria.SelectedText),
                    Notify(
                        "OK",
                        NotificationType.Success
                    );
                    UpdateContext({varLoading: true}),
                    Notify(
                        "Rellene todo el campo para agregar admin",
                        NotificationType.Error,
                        2000
                    )
                ),
            /*Áreas*/
                If(
                    varConfig = "Áreas",
                    If(
                        !IsBlank(TextInput3.Text),
                        "Patch Função";
                        UpdateContext({varLoading: true}),
                        Notify(
                            "Rellene todo el campo para agregar área",
                            NotificationType.Error,
                            2000
                        )
                    ),
            /*Subárea*/
                    If(
                        varConfig = "Subárea",
                        If(
                            !IsBlank(TextInput3_1.Text),
                            "Patch Função";
                            UpdateContext({varLoading: true}),
                            Notify(
                                "Rellene todo el campo para agregar Subárea",
                                NotificationType.Error,
                                2000
                            )
                        )
                    )
                )
            )
        PressedBorderColor: =ColorFade(RGBA(137, 211, 41, 1), -50%)
        PressedColor: =Black
        PressedFill: =ColorFade(Self.Fill, -15%)
        RadiusBottomLeft: =60
        RadiusBottomRight: =60
        RadiusTopLeft: =60
        RadiusTopRight: =60
        Size: =18
        Text: ="Registro"
        Tooltip: ="Registro"
        Width: =216
        X: =212
        Y: =If( varConfig <> "Administradores", 359, 417)
        ZIndex: =12

    Header_1 As Header:
        HeaderTitle: ="Configuración"
        Width: =Parent.Width
        ZIndex: =13

    TextInput3 As text:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Default: =""
        FocusedBorderThickness: =2
        Font: =Font.'Lato Light'
        FontWeight: =FontWeight.Semibold
        Height: =50
        HintText: ="Entra en el área"
        HoverBorderColor: =RGBA(0, 0, 0, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        Size: =18
        Visible: =If(varConfig = "Áreas",true,false)
        Width: =600
        X: =20
        Y: =287
        ZIndex: =14

    TextInput3_1 As text:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Default: =""
        FocusedBorderThickness: =2
        Font: =Font.'Lato Light'
        FontWeight: =FontWeight.Semibold
        Height: =50
        HintText: ="Entra en el subárea"
        HoverBorderColor: =RGBA(0, 0, 0, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        Size: =18
        Visible: =If(varConfig = "Subárea",true,false)
        Width: =600
        X: =20
        Y: =287
        ZIndex: =15

    Componet_Loading As Loading:
        Visible: =varLoading
        Y: =85
        ZIndex: =16

    TimerLoading As timer:
        Duration: =3000
        Height: =70
        OnTimerEnd: |-
            =UpdateContext({varLoading:false})
        OnTimerStart: =
        Start: =varLoading
        Visible: =false
        Width: =280
        X: =360
        ZIndex: =17

    Group6_1 As group:
        Height: =5
        Width: =5
        X: =60
        Y: =60
        ZIndex: =23

        Icon1_4 As icon.Home:
            Color: =RGBA(0, 188, 255, 1)
            FocusedBorderThickness: =1
            Icon: =Icon.Home
            OnSelect: =Navigate(Home,ScreenTransition.Fade)
            Tooltip: ="Inicio"
            X: =163
            Y: =1058
            ZIndex: =18

        Icon2_4 As icon.Settings:
            Color: =RGBA(0, 188, 255, 1)
            FocusedBorderThickness: =1
            Icon: =Icon.Settings
            OnSelect: =Navigate(Config,ScreenTransition.Fade)
            Tooltip: ="Configuración"
            X: =246
            Y: =1058
            ZIndex: =19

        Image7_1 As image:
            BorderColor: =RGBA(0, 188, 255, 1)
            BorderThickness: =2
            Height: =64
            Image: =Image7.Image
            RadiusBottomLeft: =100
            RadiusBottomRight: =100
            RadiusTopLeft: =100
            RadiusTopRight: =100
            Width: =64
            X: =329
            Y: =1058
            ZIndex: =20

        Button2_1 As button:
            BorderColor: =RGBA(0, 188, 255, 1)
            Fill: =RGBA(0, 0, 0, 0)
            FocusedBorderThickness: =3
            Height: =64
            HoverFill: =RGBA(255, 255, 255, 0.5)
            OnSelect: =Navigate(User,ScreenTransition.Fade)
            RadiusBottomLeft: =100
            RadiusBottomRight: =100
            RadiusTopLeft: =100
            RadiusTopRight: =100
            Size: =24
            Text: =""
            Tooltip: ="Usuario"
            Width: =64
            X: =329
            Y: =1058
            ZIndex: =21

        Icon8_1 As icon.Sync:
            BorderColor: =RGBA(0, 188, 255, 1)
            Color: =RGBA(0, 188, 255, 1)
            Icon: =Icon.Sync
            OnSelect: =Navigate(SyncPanel,ScreenTransition.Fade)
            X: =414
            Y: =1058
            ZIndex: =22

